project:
  type: website
  preview:
    port: 3333
    browser: true
    watch-inputs: false
    navigate: true

  render: 
    - "**/*.qmd"
    - "!TP/"
    - "!exam/"
    - "!show_rstudio/"
    - "!lectures/"
  resources:
    - "lectures/output"

website:
  page-navigation: true
  title: "Biostatistiques 2"
  description: "Page d'accueil pour UE 6.7 - Biostatistiques 2"
  favicon: "images/logo.png"
  open-graph: true

  sidebar:
    background: "#005871"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    search: false
    collapse-level: 1

    contents:
        - href: index.qmd
          text: Calendrier
        - href: posit_cloud_access.qmd
          text: Accéder à Posit Cloud
        - href: course-team.qmd
          text: Équipe d'enseignement
        - section: Résumés
          contents: 
            - href: model_overview_fr.qmd
              text: Modèles
           # - href: distr_overview_fr.qmd
           #  text: Distributions 
        - href: course-links.qmd
          text: Liens utiles

  page-footer:
    right: "Cette page est créée avec 🤍 et [Quarto](https://quarto.org/)."
    left: "&copy; Droits d'auteur 2026, Andreas Eich"
    background: "#005871"

format:
  html:
    theme: [cosmo, style/style.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
publish:
  - type: gh-pages    