---
title: "UE 6.7: Biostatistiques 2"
---

```{r}
#| echo: false
#| message: false
#| warning: false

library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet(
  "https://docs.google.com/spreadsheets/d/1t-OJc26IoTlWLGWKMfqwtqbuALF0Gu-6vvtzhuE1KJE/edit?gid=0#gid=0"
)
```

```{r}
#| echo: false

d %>%
  mutate(
    `ENV-01` = as.Date(`ENV-01`),
    `ENV-02` = as.Date(`ENV-02`),
    `BIO-01` = as.Date(`BIO-01`),
    `BIO-02` = as.Date(`BIO-02`)
  ) %>%
  gt() %>%
  fmt(
    columns = c(`ENV-01`, `ENV-02`, `BIO-01`, `BIO-02`),
    fns = function(x) format(x, "%d.%m.%y")
  ) %>%
  sub_missing(
    columns = c(session, topic, slides, TP, help),
    missing_text = ""
  ) %>%
  cols_align(
    align = "center",
    columns = c(session)
  ) %>%
  cols_align(
    align = "right",
    columns = c(`ENV-01`, `ENV-02`, `BIO-01`, `BIO-02`)
  ) %>%
  cols_align(
    align = "left",
    columns = c(topic, slides, TP, help)
  ) %>%
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(
        session,
        `ENV-01`,
        `ENV-02`,
        `BIO-01`,
        `BIO-02`,
        topic,
        slides,
        TP,
        help
      )
    )
  ) %>%
  fmt_markdown(
    columns = c(topic, slides, TP, help)
  ) %>%
  cols_width(
    session ~ px(75),
    `ENV-01` ~ px(100),
    `ENV-02` ~ px(100),
    `BIO-01` ~ px(100),
    `BIO-02` ~ px(100),
    topic ~ px(300),
    slides ~ px(75),
    TP ~ px(75),
    help ~ px(75)
  ) %>%
  cols_label_with(fn = function(x) {
    janitor::make_clean_names(x, case = "title") %>%
      toupper() %>%
      stringr::str_replace_all("^|$", "**") %>%
      md()
  }) %>%
  tab_options(table.font.size = 13) %>%
  opt_row_striping()
```

