project:
  output-dir: output
  preview:
    port: 6789
footer: "[WEBSITE](https://link/)"
institute: "Université de la Polynésie française <br> UE 6.7 Biostatistiques 2"
author: "Andreas Eich"
format:
  revealjs:
    logo: "images/logo.png"
    highlight-style: a11y-light
    fig-align: center
    html-math-method: mathjax
    theme: slides.scss
    slide-number: true
    code-line-numbers: false